### ISSUE TITLE
404 - JS error

### ISSUE THREAD

**Issue by jommbee** [numero2/contao-panorama-ce#1]
Hallo,

leider gibt es eine Fehlermeldung zum Javascript dieser Erweiterung:

`Die Ressource von ".../system/modules/ce_panorama/assets/libpannellum.js" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).`

Lässt sich beheben in der Datei /elements/ContentPanorama.php, indem man ein |static anhängt.

```
// add javascripts and stylesheet to head
        if( !is_array($GLOBALS['TL_JAVASCRIPT']) || array_search('system/modules/ce_panorama/assets/libpannellum.js',$GLOBALS['TL_JAVASCRIPT']) === FALSE ) {
            $GLOBALS['TL_JAVASCRIPT'][] = 'system/modules/ce_panorama/assets/libpannellum.js|static';
        }

        if( !is_array($GLOBALS['TL_JAVASCRIPT']) || array_search('system/modules/ce_panorama/assets/pannellum.js',$GLOBALS['TL_JAVASCRIPT']) === FALSE ) {
            $GLOBALS['TL_JAVASCRIPT'][] = 'system/modules/ce_panorama/assets/pannellum.js|static';
        }
```

Gleiches gilt für die CSS Einbindung.

**Comment by bennyborn** [comment]
Da die Seite nicht öffentlich erreichbar ist (htaccess) kann ich nur vermuten woran es liegt. Schau mal in der Systemwartung und lass mal die Symlinks neu generieren. Vermutlich wird unter `example.com/system/modules/ce_panorama/assets/libpannellum.js` nicht das JavaScript ausgeliefert sondern eine 404-Seite.

**Comment by jommbee** [comment]
Hi. Hilft leider nicht. Hier eine zugängliche Installation mit dem gleichen Fehler:
https://bughunting.eccoweb.de/

**Comment by bennyborn** [comment]
Ah jetzt sehe ichs, die Datei gibt es bei uns auch einfach nicht mehr. Ist jetzt schon eine Weile her aber ich glaube wir benötigen die garnicht.

Lösche einfach mal diese Zeilen

https://github.com/numero2/contao-panorama-ce/blob/66930aec00e4e0002bbfdd5e4f4a7f03e6d15a44/elements/ContentPanorama.php#L60-L62

und beobachte ob es trotzdem läuft. Ich befürchte das ist einfach noch ein Überbleibsel das wir übersehen haben.

**Comment by jommbee** [comment]
Das funktioniert. Der Fehler ist weg. Passt also.
